#ifndef PLUQ_BUILDER_H
#define PLUQ_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef PLUQ_READER_H
#include "pluq_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#define __PluQ_ResourceType_formal_args , PluQ_ResourceType_enum_t v0
#define __PluQ_ResourceType_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, PluQ_ResourceType, PluQ_ResourceType_enum_t)

#define __PluQ_Vec3_formal_args , float v0, float v1, float v2
#define __PluQ_Vec3_call_args , v0, v1, v2
static inline PluQ_Vec3_t *PluQ_Vec3_assign(PluQ_Vec3_t *p, float v0, float v1, float v2)
{ p->x = v0; p->y = v1; p->z = v2;
  return p; }
static inline PluQ_Vec3_t *PluQ_Vec3_copy(PluQ_Vec3_t *p, const PluQ_Vec3_t *p2)
{ p->x = p2->x; p->y = p2->y; p->z = p2->z;
  return p; }
static inline PluQ_Vec3_t *PluQ_Vec3_assign_to_pe(PluQ_Vec3_t *p, float v0, float v1, float v2)
{ flatbuffers_float_assign_to_pe(&p->x, v0); flatbuffers_float_assign_to_pe(&p->y, v1); flatbuffers_float_assign_to_pe(&p->z, v2);
  return p; }
static inline PluQ_Vec3_t *PluQ_Vec3_copy_to_pe(PluQ_Vec3_t *p, const PluQ_Vec3_t *p2)
{ flatbuffers_float_copy_to_pe(&p->x, &p2->x); flatbuffers_float_copy_to_pe(&p->y, &p2->y); flatbuffers_float_copy_to_pe(&p->z, &p2->z);
  return p; }
static inline PluQ_Vec3_t *PluQ_Vec3_assign_from_pe(PluQ_Vec3_t *p, float v0, float v1, float v2)
{ flatbuffers_float_assign_from_pe(&p->x, v0); flatbuffers_float_assign_from_pe(&p->y, v1); flatbuffers_float_assign_from_pe(&p->z, v2);
  return p; }
static inline PluQ_Vec3_t *PluQ_Vec3_copy_from_pe(PluQ_Vec3_t *p, const PluQ_Vec3_t *p2)
{ flatbuffers_float_copy_from_pe(&p->x, &p2->x); flatbuffers_float_copy_from_pe(&p->y, &p2->y); flatbuffers_float_copy_from_pe(&p->z, &p2->z);
  return p; }
__flatbuffers_build_struct(flatbuffers_, PluQ_Vec3, 12, 4, PluQ_Vec3_file_identifier, PluQ_Vec3_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, PluQ_Vec3, PluQ_Vec3_t)

typedef flatbuffers_union_ref_t PluQ_ResourceData_union_ref_t;
typedef flatbuffers_union_vec_ref_t PluQ_ResourceData_union_vec_ref_t;
static PluQ_ResourceData_union_ref_t PluQ_ResourceData_clone(flatbuffers_builder_t *B, PluQ_ResourceData_union_t t);
typedef flatbuffers_union_ref_t PluQ_GameplayEvent_union_ref_t;
typedef flatbuffers_union_vec_ref_t PluQ_GameplayEvent_union_vec_ref_t;
static PluQ_GameplayEvent_union_ref_t PluQ_GameplayEvent_clone(flatbuffers_builder_t *B, PluQ_GameplayEvent_union_t t);

static const flatbuffers_voffset_t __PluQ_ResourceRequest_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_ResourceRequest_ref_t;
static PluQ_ResourceRequest_ref_t PluQ_ResourceRequest_clone(flatbuffers_builder_t *B, PluQ_ResourceRequest_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_ResourceRequest, 3)

static const flatbuffers_voffset_t __PluQ_Texture_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_Texture_ref_t;
static PluQ_Texture_ref_t PluQ_Texture_clone(flatbuffers_builder_t *B, PluQ_Texture_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_Texture, 6)

static const flatbuffers_voffset_t __PluQ_Model_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_Model_ref_t;
static PluQ_Model_ref_t PluQ_Model_clone(flatbuffers_builder_t *B, PluQ_Model_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_Model, 9)

static const flatbuffers_voffset_t __PluQ_BSPVertices_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_BSPVertices_ref_t;
static PluQ_BSPVertices_ref_t PluQ_BSPVertices_clone(flatbuffers_builder_t *B, PluQ_BSPVertices_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_BSPVertices, 1)

static const flatbuffers_voffset_t __PluQ_BSPFace_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_BSPFace_ref_t;
static PluQ_BSPFace_ref_t PluQ_BSPFace_clone(flatbuffers_builder_t *B, PluQ_BSPFace_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_BSPFace, 7)

static const flatbuffers_voffset_t __PluQ_BSPFaces_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_BSPFaces_ref_t;
static PluQ_BSPFaces_ref_t PluQ_BSPFaces_clone(flatbuffers_builder_t *B, PluQ_BSPFaces_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_BSPFaces, 1)

static const flatbuffers_voffset_t __PluQ_Lightmap_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_Lightmap_ref_t;
static PluQ_Lightmap_ref_t PluQ_Lightmap_clone(flatbuffers_builder_t *B, PluQ_Lightmap_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_Lightmap, 4)

static const flatbuffers_voffset_t __PluQ_ResourceInfo_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_ResourceInfo_ref_t;
static PluQ_ResourceInfo_ref_t PluQ_ResourceInfo_clone(flatbuffers_builder_t *B, PluQ_ResourceInfo_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_ResourceInfo, 4)

static const flatbuffers_voffset_t __PluQ_ResourceResponse_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_ResourceResponse_ref_t;
static PluQ_ResourceResponse_ref_t PluQ_ResourceResponse_clone(flatbuffers_builder_t *B, PluQ_ResourceResponse_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_ResourceResponse, 3)

static const flatbuffers_voffset_t __PluQ_MapChanged_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_MapChanged_ref_t;
static PluQ_MapChanged_ref_t PluQ_MapChanged_clone(flatbuffers_builder_t *B, PluQ_MapChanged_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_MapChanged, 2)

static const flatbuffers_voffset_t __PluQ_Disconnected_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_Disconnected_ref_t;
static PluQ_Disconnected_ref_t PluQ_Disconnected_clone(flatbuffers_builder_t *B, PluQ_Disconnected_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_Disconnected, 1)

static const flatbuffers_voffset_t __PluQ_Entity_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_Entity_ref_t;
static PluQ_Entity_ref_t PluQ_Entity_clone(flatbuffers_builder_t *B, PluQ_Entity_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_Entity, 8)

static const flatbuffers_voffset_t __PluQ_FrameUpdate_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_FrameUpdate_ref_t;
static PluQ_FrameUpdate_ref_t PluQ_FrameUpdate_clone(flatbuffers_builder_t *B, PluQ_FrameUpdate_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_FrameUpdate, 11)

static const flatbuffers_voffset_t __PluQ_GameplayMessage_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_GameplayMessage_ref_t;
static PluQ_GameplayMessage_ref_t PluQ_GameplayMessage_clone(flatbuffers_builder_t *B, PluQ_GameplayMessage_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_GameplayMessage, 2)

static const flatbuffers_voffset_t __PluQ_InputCommand_required[] = { 0 };
typedef flatbuffers_ref_t PluQ_InputCommand_ref_t;
static PluQ_InputCommand_ref_t PluQ_InputCommand_clone(flatbuffers_builder_t *B, PluQ_InputCommand_table_t t);
__flatbuffers_build_table(flatbuffers_, PluQ_InputCommand, 9)

#define __PluQ_ResourceRequest_formal_args , PluQ_ResourceType_enum_t v0, uint32_t v1, flatbuffers_string_ref_t v2
#define __PluQ_ResourceRequest_call_args , v0, v1, v2
static inline PluQ_ResourceRequest_ref_t PluQ_ResourceRequest_create(flatbuffers_builder_t *B __PluQ_ResourceRequest_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_ResourceRequest, PluQ_ResourceRequest_file_identifier, PluQ_ResourceRequest_type_identifier)

#define __PluQ_Texture_formal_args ,\
  uint32_t v0, flatbuffers_string_ref_t v1, uint16_t v2, uint16_t v3, int8_t v4, flatbuffers_uint8_vec_ref_t v5
#define __PluQ_Texture_call_args ,\
  v0, v1, v2, v3, v4, v5
static inline PluQ_Texture_ref_t PluQ_Texture_create(flatbuffers_builder_t *B __PluQ_Texture_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_Texture, PluQ_Texture_file_identifier, PluQ_Texture_type_identifier)

#define __PluQ_Model_formal_args ,\
  uint32_t v0, flatbuffers_string_ref_t v1, uint32_t v2, uint32_t v3,\
  uint32_t v4, flatbuffers_float_vec_ref_t v5, flatbuffers_uint16_vec_ref_t v6, flatbuffers_float_vec_ref_t v7, flatbuffers_float_vec_ref_t v8
#define __PluQ_Model_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7, v8
static inline PluQ_Model_ref_t PluQ_Model_create(flatbuffers_builder_t *B __PluQ_Model_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_Model, PluQ_Model_file_identifier, PluQ_Model_type_identifier)

#define __PluQ_BSPVertices_formal_args , PluQ_Vec3_vec_ref_t v0
#define __PluQ_BSPVertices_call_args , v0
static inline PluQ_BSPVertices_ref_t PluQ_BSPVertices_create(flatbuffers_builder_t *B __PluQ_BSPVertices_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_BSPVertices, PluQ_BSPVertices_file_identifier, PluQ_BSPVertices_type_identifier)

#define __PluQ_BSPFace_formal_args ,\
  uint32_t v0, int8_t v1, uint32_t v2, uint16_t v3,\
  uint16_t v4, uint32_t v5, flatbuffers_int8_vec_ref_t v6
#define __PluQ_BSPFace_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6
static inline PluQ_BSPFace_ref_t PluQ_BSPFace_create(flatbuffers_builder_t *B __PluQ_BSPFace_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_BSPFace, PluQ_BSPFace_file_identifier, PluQ_BSPFace_type_identifier)

#define __PluQ_BSPFaces_formal_args , PluQ_BSPFace_vec_ref_t v0
#define __PluQ_BSPFaces_call_args , v0
static inline PluQ_BSPFaces_ref_t PluQ_BSPFaces_create(flatbuffers_builder_t *B __PluQ_BSPFaces_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_BSPFaces, PluQ_BSPFaces_file_identifier, PluQ_BSPFaces_type_identifier)

#define __PluQ_Lightmap_formal_args , uint32_t v0, uint16_t v1, uint16_t v2, flatbuffers_uint8_vec_ref_t v3
#define __PluQ_Lightmap_call_args , v0, v1, v2, v3
static inline PluQ_Lightmap_ref_t PluQ_Lightmap_create(flatbuffers_builder_t *B __PluQ_Lightmap_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_Lightmap, PluQ_Lightmap_file_identifier, PluQ_Lightmap_type_identifier)

#define __PluQ_ResourceInfo_formal_args , uint32_t v0, PluQ_ResourceType_enum_t v1, flatbuffers_string_ref_t v2, uint32_t v3
#define __PluQ_ResourceInfo_call_args , v0, v1, v2, v3
static inline PluQ_ResourceInfo_ref_t PluQ_ResourceInfo_create(flatbuffers_builder_t *B __PluQ_ResourceInfo_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_ResourceInfo, PluQ_ResourceInfo_file_identifier, PluQ_ResourceInfo_type_identifier)

#define __PluQ_ResourceResponse_formal_args , uint32_t v0, PluQ_ResourceData_union_ref_t v2
#define __PluQ_ResourceResponse_call_args , v0, v2
static inline PluQ_ResourceResponse_ref_t PluQ_ResourceResponse_create(flatbuffers_builder_t *B __PluQ_ResourceResponse_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_ResourceResponse, PluQ_ResourceResponse_file_identifier, PluQ_ResourceResponse_type_identifier)

#define __PluQ_MapChanged_formal_args , flatbuffers_string_ref_t v0, PluQ_ResourceInfo_vec_ref_t v1
#define __PluQ_MapChanged_call_args , v0, v1
static inline PluQ_MapChanged_ref_t PluQ_MapChanged_create(flatbuffers_builder_t *B __PluQ_MapChanged_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_MapChanged, PluQ_MapChanged_file_identifier, PluQ_MapChanged_type_identifier)

#define __PluQ_Disconnected_formal_args , flatbuffers_string_ref_t v0
#define __PluQ_Disconnected_call_args , v0
static inline PluQ_Disconnected_ref_t PluQ_Disconnected_create(flatbuffers_builder_t *B __PluQ_Disconnected_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_Disconnected, PluQ_Disconnected_file_identifier, PluQ_Disconnected_type_identifier)

#define __PluQ_Entity_formal_args ,\
  PluQ_Vec3_t *v0, PluQ_Vec3_t *v1, uint16_t v2, int8_t v3,\
  int8_t v4, int8_t v5, uint32_t v6, float v7
#define __PluQ_Entity_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7
static inline PluQ_Entity_ref_t PluQ_Entity_create(flatbuffers_builder_t *B __PluQ_Entity_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_Entity, PluQ_Entity_file_identifier, PluQ_Entity_type_identifier)

#define __PluQ_FrameUpdate_formal_args ,\
  uint32_t v0, double v1, PluQ_Vec3_t *v2, PluQ_Vec3_t *v3,\
  int16_t v4, int16_t v5, int8_t v6, uint16_t v7,\
  flatbuffers_bool_t v8, flatbuffers_bool_t v9, PluQ_Entity_vec_ref_t v10
#define __PluQ_FrameUpdate_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10
static inline PluQ_FrameUpdate_ref_t PluQ_FrameUpdate_create(flatbuffers_builder_t *B __PluQ_FrameUpdate_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_FrameUpdate, PluQ_FrameUpdate_file_identifier, PluQ_FrameUpdate_type_identifier)

#define __PluQ_GameplayMessage_formal_args , PluQ_GameplayEvent_union_ref_t v1
#define __PluQ_GameplayMessage_call_args , v1
static inline PluQ_GameplayMessage_ref_t PluQ_GameplayMessage_create(flatbuffers_builder_t *B __PluQ_GameplayMessage_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_GameplayMessage, PluQ_GameplayMessage_file_identifier, PluQ_GameplayMessage_type_identifier)

#define __PluQ_InputCommand_formal_args ,\
  uint32_t v0, double v1, float v2, float v3,\
  float v4, PluQ_Vec3_t *v5, uint32_t v6, int8_t v7, flatbuffers_string_ref_t v8
#define __PluQ_InputCommand_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7, v8
static inline PluQ_InputCommand_ref_t PluQ_InputCommand_create(flatbuffers_builder_t *B __PluQ_InputCommand_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PluQ_InputCommand, PluQ_InputCommand_file_identifier, PluQ_InputCommand_type_identifier)

static inline PluQ_ResourceData_union_ref_t PluQ_ResourceData_as_NONE(void)
{ PluQ_ResourceData_union_ref_t uref; uref.type = PluQ_ResourceData_NONE; uref.value = 0; return uref; }
static inline PluQ_ResourceData_union_ref_t PluQ_ResourceData_as_Texture(PluQ_Texture_ref_t ref)
{ PluQ_ResourceData_union_ref_t uref; uref.type = PluQ_ResourceData_Texture; uref.value = ref; return uref; }
static inline PluQ_ResourceData_union_ref_t PluQ_ResourceData_as_Model(PluQ_Model_ref_t ref)
{ PluQ_ResourceData_union_ref_t uref; uref.type = PluQ_ResourceData_Model; uref.value = ref; return uref; }
static inline PluQ_ResourceData_union_ref_t PluQ_ResourceData_as_BSPVertices(PluQ_BSPVertices_ref_t ref)
{ PluQ_ResourceData_union_ref_t uref; uref.type = PluQ_ResourceData_BSPVertices; uref.value = ref; return uref; }
static inline PluQ_ResourceData_union_ref_t PluQ_ResourceData_as_BSPFaces(PluQ_BSPFaces_ref_t ref)
{ PluQ_ResourceData_union_ref_t uref; uref.type = PluQ_ResourceData_BSPFaces; uref.value = ref; return uref; }
static inline PluQ_ResourceData_union_ref_t PluQ_ResourceData_as_Lightmap(PluQ_Lightmap_ref_t ref)
{ PluQ_ResourceData_union_ref_t uref; uref.type = PluQ_ResourceData_Lightmap; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, PluQ_ResourceData)

static PluQ_ResourceData_union_ref_t PluQ_ResourceData_clone(flatbuffers_builder_t *B, PluQ_ResourceData_union_t u)
{
    switch (u.type) {
    case 1: return PluQ_ResourceData_as_Texture(PluQ_Texture_clone(B, (PluQ_Texture_table_t)u.value));
    case 2: return PluQ_ResourceData_as_Model(PluQ_Model_clone(B, (PluQ_Model_table_t)u.value));
    case 3: return PluQ_ResourceData_as_BSPVertices(PluQ_BSPVertices_clone(B, (PluQ_BSPVertices_table_t)u.value));
    case 4: return PluQ_ResourceData_as_BSPFaces(PluQ_BSPFaces_clone(B, (PluQ_BSPFaces_table_t)u.value));
    case 5: return PluQ_ResourceData_as_Lightmap(PluQ_Lightmap_clone(B, (PluQ_Lightmap_table_t)u.value));
    default: return PluQ_ResourceData_as_NONE();
    }
}

static inline PluQ_GameplayEvent_union_ref_t PluQ_GameplayEvent_as_NONE(void)
{ PluQ_GameplayEvent_union_ref_t uref; uref.type = PluQ_GameplayEvent_NONE; uref.value = 0; return uref; }
static inline PluQ_GameplayEvent_union_ref_t PluQ_GameplayEvent_as_MapChanged(PluQ_MapChanged_ref_t ref)
{ PluQ_GameplayEvent_union_ref_t uref; uref.type = PluQ_GameplayEvent_MapChanged; uref.value = ref; return uref; }
static inline PluQ_GameplayEvent_union_ref_t PluQ_GameplayEvent_as_FrameUpdate(PluQ_FrameUpdate_ref_t ref)
{ PluQ_GameplayEvent_union_ref_t uref; uref.type = PluQ_GameplayEvent_FrameUpdate; uref.value = ref; return uref; }
static inline PluQ_GameplayEvent_union_ref_t PluQ_GameplayEvent_as_Disconnected(PluQ_Disconnected_ref_t ref)
{ PluQ_GameplayEvent_union_ref_t uref; uref.type = PluQ_GameplayEvent_Disconnected; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, PluQ_GameplayEvent)

static PluQ_GameplayEvent_union_ref_t PluQ_GameplayEvent_clone(flatbuffers_builder_t *B, PluQ_GameplayEvent_union_t u)
{
    switch (u.type) {
    case 1: return PluQ_GameplayEvent_as_MapChanged(PluQ_MapChanged_clone(B, (PluQ_MapChanged_table_t)u.value));
    case 2: return PluQ_GameplayEvent_as_FrameUpdate(PluQ_FrameUpdate_clone(B, (PluQ_FrameUpdate_table_t)u.value));
    case 3: return PluQ_GameplayEvent_as_Disconnected(PluQ_Disconnected_clone(B, (PluQ_Disconnected_table_t)u.value));
    default: return PluQ_GameplayEvent_as_NONE();
    }
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PluQ_ResourceRequest_resource_type, PluQ_ResourceType, PluQ_ResourceType_enum_t, 1, 1, INT8_C(0), PluQ_ResourceRequest)
__flatbuffers_build_scalar_field(1, flatbuffers_, PluQ_ResourceRequest_resource_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_ResourceRequest)
__flatbuffers_build_string_field(2, flatbuffers_, PluQ_ResourceRequest_resource_name, PluQ_ResourceRequest)

static inline PluQ_ResourceRequest_ref_t PluQ_ResourceRequest_create(flatbuffers_builder_t *B __PluQ_ResourceRequest_formal_args)
{
    if (PluQ_ResourceRequest_start(B)
        || PluQ_ResourceRequest_resource_id_add(B, v1)
        || PluQ_ResourceRequest_resource_name_add(B, v2)
        || PluQ_ResourceRequest_resource_type_add(B, v0)) {
        return 0;
    }
    return PluQ_ResourceRequest_end(B);
}

static PluQ_ResourceRequest_ref_t PluQ_ResourceRequest_clone(flatbuffers_builder_t *B, PluQ_ResourceRequest_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_ResourceRequest_start(B)
        || PluQ_ResourceRequest_resource_id_pick(B, t)
        || PluQ_ResourceRequest_resource_name_pick(B, t)
        || PluQ_ResourceRequest_resource_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_ResourceRequest_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PluQ_Texture_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_Texture)
__flatbuffers_build_string_field(1, flatbuffers_, PluQ_Texture_name, PluQ_Texture)
__flatbuffers_build_scalar_field(2, flatbuffers_, PluQ_Texture_width, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PluQ_Texture)
__flatbuffers_build_scalar_field(3, flatbuffers_, PluQ_Texture_height, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PluQ_Texture)
__flatbuffers_build_scalar_field(4, flatbuffers_, PluQ_Texture_format, flatbuffers_int8, int8_t, 1, 1, INT8_C(0), PluQ_Texture)
__flatbuffers_build_vector_field(5, flatbuffers_, PluQ_Texture_pixels, flatbuffers_uint8, uint8_t, PluQ_Texture)

static inline PluQ_Texture_ref_t PluQ_Texture_create(flatbuffers_builder_t *B __PluQ_Texture_formal_args)
{
    if (PluQ_Texture_start(B)
        || PluQ_Texture_id_add(B, v0)
        || PluQ_Texture_name_add(B, v1)
        || PluQ_Texture_pixels_add(B, v5)
        || PluQ_Texture_width_add(B, v2)
        || PluQ_Texture_height_add(B, v3)
        || PluQ_Texture_format_add(B, v4)) {
        return 0;
    }
    return PluQ_Texture_end(B);
}

static PluQ_Texture_ref_t PluQ_Texture_clone(flatbuffers_builder_t *B, PluQ_Texture_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_Texture_start(B)
        || PluQ_Texture_id_pick(B, t)
        || PluQ_Texture_name_pick(B, t)
        || PluQ_Texture_pixels_pick(B, t)
        || PluQ_Texture_width_pick(B, t)
        || PluQ_Texture_height_pick(B, t)
        || PluQ_Texture_format_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_Texture_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PluQ_Model_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_Model)
__flatbuffers_build_string_field(1, flatbuffers_, PluQ_Model_name, PluQ_Model)
__flatbuffers_build_scalar_field(2, flatbuffers_, PluQ_Model_num_vertices, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_Model)
__flatbuffers_build_scalar_field(3, flatbuffers_, PluQ_Model_num_triangles, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_Model)
__flatbuffers_build_scalar_field(4, flatbuffers_, PluQ_Model_num_frames, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_Model)
__flatbuffers_build_vector_field(5, flatbuffers_, PluQ_Model_vertices, flatbuffers_float, float, PluQ_Model)
__flatbuffers_build_vector_field(6, flatbuffers_, PluQ_Model_triangles, flatbuffers_uint16, uint16_t, PluQ_Model)
__flatbuffers_build_vector_field(7, flatbuffers_, PluQ_Model_texcoords, flatbuffers_float, float, PluQ_Model)
__flatbuffers_build_vector_field(8, flatbuffers_, PluQ_Model_normals, flatbuffers_float, float, PluQ_Model)

static inline PluQ_Model_ref_t PluQ_Model_create(flatbuffers_builder_t *B __PluQ_Model_formal_args)
{
    if (PluQ_Model_start(B)
        || PluQ_Model_id_add(B, v0)
        || PluQ_Model_name_add(B, v1)
        || PluQ_Model_num_vertices_add(B, v2)
        || PluQ_Model_num_triangles_add(B, v3)
        || PluQ_Model_num_frames_add(B, v4)
        || PluQ_Model_vertices_add(B, v5)
        || PluQ_Model_triangles_add(B, v6)
        || PluQ_Model_texcoords_add(B, v7)
        || PluQ_Model_normals_add(B, v8)) {
        return 0;
    }
    return PluQ_Model_end(B);
}

static PluQ_Model_ref_t PluQ_Model_clone(flatbuffers_builder_t *B, PluQ_Model_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_Model_start(B)
        || PluQ_Model_id_pick(B, t)
        || PluQ_Model_name_pick(B, t)
        || PluQ_Model_num_vertices_pick(B, t)
        || PluQ_Model_num_triangles_pick(B, t)
        || PluQ_Model_num_frames_pick(B, t)
        || PluQ_Model_vertices_pick(B, t)
        || PluQ_Model_triangles_pick(B, t)
        || PluQ_Model_texcoords_pick(B, t)
        || PluQ_Model_normals_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_Model_end(B));
}

__flatbuffers_build_vector_field(0, flatbuffers_, PluQ_BSPVertices_vertices, PluQ_Vec3, PluQ_Vec3_t, PluQ_BSPVertices)

static inline PluQ_BSPVertices_ref_t PluQ_BSPVertices_create(flatbuffers_builder_t *B __PluQ_BSPVertices_formal_args)
{
    if (PluQ_BSPVertices_start(B)
        || PluQ_BSPVertices_vertices_add(B, v0)) {
        return 0;
    }
    return PluQ_BSPVertices_end(B);
}

static PluQ_BSPVertices_ref_t PluQ_BSPVertices_clone(flatbuffers_builder_t *B, PluQ_BSPVertices_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_BSPVertices_start(B)
        || PluQ_BSPVertices_vertices_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_BSPVertices_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PluQ_BSPFace_plane_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_BSPFace)
__flatbuffers_build_scalar_field(1, flatbuffers_, PluQ_BSPFace_side, flatbuffers_int8, int8_t, 1, 1, INT8_C(0), PluQ_BSPFace)
__flatbuffers_build_scalar_field(2, flatbuffers_, PluQ_BSPFace_first_edge, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_BSPFace)
__flatbuffers_build_scalar_field(3, flatbuffers_, PluQ_BSPFace_num_edges, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PluQ_BSPFace)
__flatbuffers_build_scalar_field(4, flatbuffers_, PluQ_BSPFace_texture_id, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PluQ_BSPFace)
__flatbuffers_build_scalar_field(5, flatbuffers_, PluQ_BSPFace_lightmap_offset, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_BSPFace)
__flatbuffers_build_vector_field(6, flatbuffers_, PluQ_BSPFace_styles, flatbuffers_int8, int8_t, PluQ_BSPFace)

static inline PluQ_BSPFace_ref_t PluQ_BSPFace_create(flatbuffers_builder_t *B __PluQ_BSPFace_formal_args)
{
    if (PluQ_BSPFace_start(B)
        || PluQ_BSPFace_plane_id_add(B, v0)
        || PluQ_BSPFace_first_edge_add(B, v2)
        || PluQ_BSPFace_lightmap_offset_add(B, v5)
        || PluQ_BSPFace_styles_add(B, v6)
        || PluQ_BSPFace_num_edges_add(B, v3)
        || PluQ_BSPFace_texture_id_add(B, v4)
        || PluQ_BSPFace_side_add(B, v1)) {
        return 0;
    }
    return PluQ_BSPFace_end(B);
}

static PluQ_BSPFace_ref_t PluQ_BSPFace_clone(flatbuffers_builder_t *B, PluQ_BSPFace_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_BSPFace_start(B)
        || PluQ_BSPFace_plane_id_pick(B, t)
        || PluQ_BSPFace_first_edge_pick(B, t)
        || PluQ_BSPFace_lightmap_offset_pick(B, t)
        || PluQ_BSPFace_styles_pick(B, t)
        || PluQ_BSPFace_num_edges_pick(B, t)
        || PluQ_BSPFace_texture_id_pick(B, t)
        || PluQ_BSPFace_side_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_BSPFace_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, PluQ_BSPFaces_faces, PluQ_BSPFace, PluQ_BSPFaces)

static inline PluQ_BSPFaces_ref_t PluQ_BSPFaces_create(flatbuffers_builder_t *B __PluQ_BSPFaces_formal_args)
{
    if (PluQ_BSPFaces_start(B)
        || PluQ_BSPFaces_faces_add(B, v0)) {
        return 0;
    }
    return PluQ_BSPFaces_end(B);
}

static PluQ_BSPFaces_ref_t PluQ_BSPFaces_clone(flatbuffers_builder_t *B, PluQ_BSPFaces_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_BSPFaces_start(B)
        || PluQ_BSPFaces_faces_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_BSPFaces_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PluQ_Lightmap_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_Lightmap)
__flatbuffers_build_scalar_field(1, flatbuffers_, PluQ_Lightmap_width, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PluQ_Lightmap)
__flatbuffers_build_scalar_field(2, flatbuffers_, PluQ_Lightmap_height, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PluQ_Lightmap)
__flatbuffers_build_vector_field(3, flatbuffers_, PluQ_Lightmap_data, flatbuffers_uint8, uint8_t, PluQ_Lightmap)

static inline PluQ_Lightmap_ref_t PluQ_Lightmap_create(flatbuffers_builder_t *B __PluQ_Lightmap_formal_args)
{
    if (PluQ_Lightmap_start(B)
        || PluQ_Lightmap_id_add(B, v0)
        || PluQ_Lightmap_data_add(B, v3)
        || PluQ_Lightmap_width_add(B, v1)
        || PluQ_Lightmap_height_add(B, v2)) {
        return 0;
    }
    return PluQ_Lightmap_end(B);
}

static PluQ_Lightmap_ref_t PluQ_Lightmap_clone(flatbuffers_builder_t *B, PluQ_Lightmap_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_Lightmap_start(B)
        || PluQ_Lightmap_id_pick(B, t)
        || PluQ_Lightmap_data_pick(B, t)
        || PluQ_Lightmap_width_pick(B, t)
        || PluQ_Lightmap_height_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_Lightmap_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PluQ_ResourceInfo_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_ResourceInfo)
__flatbuffers_build_scalar_field(1, flatbuffers_, PluQ_ResourceInfo_type, PluQ_ResourceType, PluQ_ResourceType_enum_t, 1, 1, INT8_C(0), PluQ_ResourceInfo)
__flatbuffers_build_string_field(2, flatbuffers_, PluQ_ResourceInfo_name, PluQ_ResourceInfo)
__flatbuffers_build_scalar_field(3, flatbuffers_, PluQ_ResourceInfo_size, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_ResourceInfo)

static inline PluQ_ResourceInfo_ref_t PluQ_ResourceInfo_create(flatbuffers_builder_t *B __PluQ_ResourceInfo_formal_args)
{
    if (PluQ_ResourceInfo_start(B)
        || PluQ_ResourceInfo_id_add(B, v0)
        || PluQ_ResourceInfo_name_add(B, v2)
        || PluQ_ResourceInfo_size_add(B, v3)
        || PluQ_ResourceInfo_type_add(B, v1)) {
        return 0;
    }
    return PluQ_ResourceInfo_end(B);
}

static PluQ_ResourceInfo_ref_t PluQ_ResourceInfo_clone(flatbuffers_builder_t *B, PluQ_ResourceInfo_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_ResourceInfo_start(B)
        || PluQ_ResourceInfo_id_pick(B, t)
        || PluQ_ResourceInfo_name_pick(B, t)
        || PluQ_ResourceInfo_size_pick(B, t)
        || PluQ_ResourceInfo_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_ResourceInfo_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PluQ_ResourceResponse_resource_id, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_ResourceResponse)
__flatbuffers_build_union_field(2, flatbuffers_, PluQ_ResourceResponse_data, PluQ_ResourceData, PluQ_ResourceResponse)
__flatbuffers_build_union_table_value_field(flatbuffers_, PluQ_ResourceResponse_data, PluQ_ResourceData, Texture, PluQ_Texture)
__flatbuffers_build_union_table_value_field(flatbuffers_, PluQ_ResourceResponse_data, PluQ_ResourceData, Model, PluQ_Model)
__flatbuffers_build_union_table_value_field(flatbuffers_, PluQ_ResourceResponse_data, PluQ_ResourceData, BSPVertices, PluQ_BSPVertices)
__flatbuffers_build_union_table_value_field(flatbuffers_, PluQ_ResourceResponse_data, PluQ_ResourceData, BSPFaces, PluQ_BSPFaces)
__flatbuffers_build_union_table_value_field(flatbuffers_, PluQ_ResourceResponse_data, PluQ_ResourceData, Lightmap, PluQ_Lightmap)

static inline PluQ_ResourceResponse_ref_t PluQ_ResourceResponse_create(flatbuffers_builder_t *B __PluQ_ResourceResponse_formal_args)
{
    if (PluQ_ResourceResponse_start(B)
        || PluQ_ResourceResponse_resource_id_add(B, v0)
        || PluQ_ResourceResponse_data_add_value(B, v2)
        || PluQ_ResourceResponse_data_add_type(B, v2.type)) {
        return 0;
    }
    return PluQ_ResourceResponse_end(B);
}

static PluQ_ResourceResponse_ref_t PluQ_ResourceResponse_clone(flatbuffers_builder_t *B, PluQ_ResourceResponse_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_ResourceResponse_start(B)
        || PluQ_ResourceResponse_resource_id_pick(B, t)
        || PluQ_ResourceResponse_data_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_ResourceResponse_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PluQ_MapChanged_mapname, PluQ_MapChanged)
__flatbuffers_build_table_vector_field(1, flatbuffers_, PluQ_MapChanged_resources, PluQ_ResourceInfo, PluQ_MapChanged)

static inline PluQ_MapChanged_ref_t PluQ_MapChanged_create(flatbuffers_builder_t *B __PluQ_MapChanged_formal_args)
{
    if (PluQ_MapChanged_start(B)
        || PluQ_MapChanged_mapname_add(B, v0)
        || PluQ_MapChanged_resources_add(B, v1)) {
        return 0;
    }
    return PluQ_MapChanged_end(B);
}

static PluQ_MapChanged_ref_t PluQ_MapChanged_clone(flatbuffers_builder_t *B, PluQ_MapChanged_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_MapChanged_start(B)
        || PluQ_MapChanged_mapname_pick(B, t)
        || PluQ_MapChanged_resources_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_MapChanged_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PluQ_Disconnected_reason, PluQ_Disconnected)

static inline PluQ_Disconnected_ref_t PluQ_Disconnected_create(flatbuffers_builder_t *B __PluQ_Disconnected_formal_args)
{
    if (PluQ_Disconnected_start(B)
        || PluQ_Disconnected_reason_add(B, v0)) {
        return 0;
    }
    return PluQ_Disconnected_end(B);
}

static PluQ_Disconnected_ref_t PluQ_Disconnected_clone(flatbuffers_builder_t *B, PluQ_Disconnected_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_Disconnected_start(B)
        || PluQ_Disconnected_reason_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_Disconnected_end(B));
}

__flatbuffers_build_struct_field(0, flatbuffers_, PluQ_Entity_origin, PluQ_Vec3, 12, 4, PluQ_Entity)
__flatbuffers_build_struct_field(1, flatbuffers_, PluQ_Entity_angles, PluQ_Vec3, 12, 4, PluQ_Entity)
__flatbuffers_build_scalar_field(2, flatbuffers_, PluQ_Entity_model_id, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PluQ_Entity)
__flatbuffers_build_scalar_field(3, flatbuffers_, PluQ_Entity_frame, flatbuffers_int8, int8_t, 1, 1, INT8_C(0), PluQ_Entity)
__flatbuffers_build_scalar_field(4, flatbuffers_, PluQ_Entity_colormap, flatbuffers_int8, int8_t, 1, 1, INT8_C(0), PluQ_Entity)
__flatbuffers_build_scalar_field(5, flatbuffers_, PluQ_Entity_skin, flatbuffers_int8, int8_t, 1, 1, INT8_C(0), PluQ_Entity)
__flatbuffers_build_scalar_field(6, flatbuffers_, PluQ_Entity_effects, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_Entity)
__flatbuffers_build_scalar_field(7, flatbuffers_, PluQ_Entity_alpha, flatbuffers_float, float, 4, 4, 0.00000000f, PluQ_Entity)

static inline PluQ_Entity_ref_t PluQ_Entity_create(flatbuffers_builder_t *B __PluQ_Entity_formal_args)
{
    if (PluQ_Entity_start(B)
        || PluQ_Entity_origin_add(B, v0)
        || PluQ_Entity_angles_add(B, v1)
        || PluQ_Entity_effects_add(B, v6)
        || PluQ_Entity_alpha_add(B, v7)
        || PluQ_Entity_model_id_add(B, v2)
        || PluQ_Entity_frame_add(B, v3)
        || PluQ_Entity_colormap_add(B, v4)
        || PluQ_Entity_skin_add(B, v5)) {
        return 0;
    }
    return PluQ_Entity_end(B);
}

static PluQ_Entity_ref_t PluQ_Entity_clone(flatbuffers_builder_t *B, PluQ_Entity_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_Entity_start(B)
        || PluQ_Entity_origin_pick(B, t)
        || PluQ_Entity_angles_pick(B, t)
        || PluQ_Entity_effects_pick(B, t)
        || PluQ_Entity_alpha_pick(B, t)
        || PluQ_Entity_model_id_pick(B, t)
        || PluQ_Entity_frame_pick(B, t)
        || PluQ_Entity_colormap_pick(B, t)
        || PluQ_Entity_skin_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_Entity_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PluQ_FrameUpdate_frame_number, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_FrameUpdate)
__flatbuffers_build_scalar_field(1, flatbuffers_, PluQ_FrameUpdate_timestamp, flatbuffers_double, double, 8, 8, 0.0000000000000000, PluQ_FrameUpdate)
__flatbuffers_build_struct_field(2, flatbuffers_, PluQ_FrameUpdate_view_origin, PluQ_Vec3, 12, 4, PluQ_FrameUpdate)
__flatbuffers_build_struct_field(3, flatbuffers_, PluQ_FrameUpdate_view_angles, PluQ_Vec3, 12, 4, PluQ_FrameUpdate)
__flatbuffers_build_scalar_field(4, flatbuffers_, PluQ_FrameUpdate_health, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PluQ_FrameUpdate)
__flatbuffers_build_scalar_field(5, flatbuffers_, PluQ_FrameUpdate_armor, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PluQ_FrameUpdate)
__flatbuffers_build_scalar_field(6, flatbuffers_, PluQ_FrameUpdate_weapon, flatbuffers_int8, int8_t, 1, 1, INT8_C(0), PluQ_FrameUpdate)
__flatbuffers_build_scalar_field(7, flatbuffers_, PluQ_FrameUpdate_ammo, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PluQ_FrameUpdate)
__flatbuffers_build_scalar_field(8, flatbuffers_, PluQ_FrameUpdate_paused, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), PluQ_FrameUpdate)
__flatbuffers_build_scalar_field(9, flatbuffers_, PluQ_FrameUpdate_in_game, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), PluQ_FrameUpdate)
__flatbuffers_build_table_vector_field(10, flatbuffers_, PluQ_FrameUpdate_entities, PluQ_Entity, PluQ_FrameUpdate)

static inline PluQ_FrameUpdate_ref_t PluQ_FrameUpdate_create(flatbuffers_builder_t *B __PluQ_FrameUpdate_formal_args)
{
    if (PluQ_FrameUpdate_start(B)
        || PluQ_FrameUpdate_timestamp_add(B, v1)
        || PluQ_FrameUpdate_frame_number_add(B, v0)
        || PluQ_FrameUpdate_view_origin_add(B, v2)
        || PluQ_FrameUpdate_view_angles_add(B, v3)
        || PluQ_FrameUpdate_entities_add(B, v10)
        || PluQ_FrameUpdate_health_add(B, v4)
        || PluQ_FrameUpdate_armor_add(B, v5)
        || PluQ_FrameUpdate_ammo_add(B, v7)
        || PluQ_FrameUpdate_weapon_add(B, v6)
        || PluQ_FrameUpdate_paused_add(B, v8)
        || PluQ_FrameUpdate_in_game_add(B, v9)) {
        return 0;
    }
    return PluQ_FrameUpdate_end(B);
}

static PluQ_FrameUpdate_ref_t PluQ_FrameUpdate_clone(flatbuffers_builder_t *B, PluQ_FrameUpdate_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_FrameUpdate_start(B)
        || PluQ_FrameUpdate_timestamp_pick(B, t)
        || PluQ_FrameUpdate_frame_number_pick(B, t)
        || PluQ_FrameUpdate_view_origin_pick(B, t)
        || PluQ_FrameUpdate_view_angles_pick(B, t)
        || PluQ_FrameUpdate_entities_pick(B, t)
        || PluQ_FrameUpdate_health_pick(B, t)
        || PluQ_FrameUpdate_armor_pick(B, t)
        || PluQ_FrameUpdate_ammo_pick(B, t)
        || PluQ_FrameUpdate_weapon_pick(B, t)
        || PluQ_FrameUpdate_paused_pick(B, t)
        || PluQ_FrameUpdate_in_game_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_FrameUpdate_end(B));
}

__flatbuffers_build_union_field(1, flatbuffers_, PluQ_GameplayMessage_event, PluQ_GameplayEvent, PluQ_GameplayMessage)
__flatbuffers_build_union_table_value_field(flatbuffers_, PluQ_GameplayMessage_event, PluQ_GameplayEvent, MapChanged, PluQ_MapChanged)
__flatbuffers_build_union_table_value_field(flatbuffers_, PluQ_GameplayMessage_event, PluQ_GameplayEvent, FrameUpdate, PluQ_FrameUpdate)
__flatbuffers_build_union_table_value_field(flatbuffers_, PluQ_GameplayMessage_event, PluQ_GameplayEvent, Disconnected, PluQ_Disconnected)

static inline PluQ_GameplayMessage_ref_t PluQ_GameplayMessage_create(flatbuffers_builder_t *B __PluQ_GameplayMessage_formal_args)
{
    if (PluQ_GameplayMessage_start(B)
        || PluQ_GameplayMessage_event_add_value(B, v1)
        || PluQ_GameplayMessage_event_add_type(B, v1.type)) {
        return 0;
    }
    return PluQ_GameplayMessage_end(B);
}

static PluQ_GameplayMessage_ref_t PluQ_GameplayMessage_clone(flatbuffers_builder_t *B, PluQ_GameplayMessage_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_GameplayMessage_start(B)
        || PluQ_GameplayMessage_event_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_GameplayMessage_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PluQ_InputCommand_sequence, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_InputCommand)
__flatbuffers_build_scalar_field(1, flatbuffers_, PluQ_InputCommand_timestamp, flatbuffers_double, double, 8, 8, 0.0000000000000000, PluQ_InputCommand)
__flatbuffers_build_scalar_field(2, flatbuffers_, PluQ_InputCommand_forward_move, flatbuffers_float, float, 4, 4, 0.00000000f, PluQ_InputCommand)
__flatbuffers_build_scalar_field(3, flatbuffers_, PluQ_InputCommand_side_move, flatbuffers_float, float, 4, 4, 0.00000000f, PluQ_InputCommand)
__flatbuffers_build_scalar_field(4, flatbuffers_, PluQ_InputCommand_up_move, flatbuffers_float, float, 4, 4, 0.00000000f, PluQ_InputCommand)
__flatbuffers_build_struct_field(5, flatbuffers_, PluQ_InputCommand_view_angles, PluQ_Vec3, 12, 4, PluQ_InputCommand)
__flatbuffers_build_scalar_field(6, flatbuffers_, PluQ_InputCommand_buttons, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), PluQ_InputCommand)
__flatbuffers_build_scalar_field(7, flatbuffers_, PluQ_InputCommand_impulse, flatbuffers_int8, int8_t, 1, 1, INT8_C(0), PluQ_InputCommand)
__flatbuffers_build_string_field(8, flatbuffers_, PluQ_InputCommand_cmd_text, PluQ_InputCommand)

static inline PluQ_InputCommand_ref_t PluQ_InputCommand_create(flatbuffers_builder_t *B __PluQ_InputCommand_formal_args)
{
    if (PluQ_InputCommand_start(B)
        || PluQ_InputCommand_timestamp_add(B, v1)
        || PluQ_InputCommand_sequence_add(B, v0)
        || PluQ_InputCommand_forward_move_add(B, v2)
        || PluQ_InputCommand_side_move_add(B, v3)
        || PluQ_InputCommand_up_move_add(B, v4)
        || PluQ_InputCommand_view_angles_add(B, v5)
        || PluQ_InputCommand_buttons_add(B, v6)
        || PluQ_InputCommand_cmd_text_add(B, v8)
        || PluQ_InputCommand_impulse_add(B, v7)) {
        return 0;
    }
    return PluQ_InputCommand_end(B);
}

static PluQ_InputCommand_ref_t PluQ_InputCommand_clone(flatbuffers_builder_t *B, PluQ_InputCommand_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PluQ_InputCommand_start(B)
        || PluQ_InputCommand_timestamp_pick(B, t)
        || PluQ_InputCommand_sequence_pick(B, t)
        || PluQ_InputCommand_forward_move_pick(B, t)
        || PluQ_InputCommand_side_move_pick(B, t)
        || PluQ_InputCommand_up_move_pick(B, t)
        || PluQ_InputCommand_view_angles_pick(B, t)
        || PluQ_InputCommand_buttons_pick(B, t)
        || PluQ_InputCommand_cmd_text_pick(B, t)
        || PluQ_InputCommand_impulse_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PluQ_InputCommand_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PLUQ_BUILDER_H */
