#ifndef PLUQ_VERIFIER_H
#define PLUQ_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef PLUQ_READER_H
#include "pluq_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int PluQ_ResourceRequest_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_Texture_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_Model_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_BSPVertices_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_BSPFace_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_BSPFaces_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_Lightmap_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_ResourceInfo_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_ResourceResponse_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_MapChanged_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_Disconnected_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_Entity_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_FrameUpdate_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_GameplayMessage_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PluQ_InputCommand_verify_table(flatcc_table_verifier_descriptor_t *td);

static int PluQ_ResourceData_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PluQ_Texture_verify_table); /* Texture */
    case 2: return flatcc_verify_union_table(ud, PluQ_Model_verify_table); /* Model */
    case 3: return flatcc_verify_union_table(ud, PluQ_BSPVertices_verify_table); /* BSPVertices */
    case 4: return flatcc_verify_union_table(ud, PluQ_BSPFaces_verify_table); /* BSPFaces */
    case 5: return flatcc_verify_union_table(ud, PluQ_Lightmap_verify_table); /* Lightmap */
    default: return flatcc_verify_ok;
    }
}

static int PluQ_GameplayEvent_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PluQ_MapChanged_verify_table); /* MapChanged */
    case 2: return flatcc_verify_union_table(ud, PluQ_FrameUpdate_verify_table); /* FrameUpdate */
    case 3: return flatcc_verify_union_table(ud, PluQ_Disconnected_verify_table); /* Disconnected */
    default: return flatcc_verify_ok;
    }
}

static inline int PluQ_Vec3_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, PluQ_Vec3_identifier, 12, 4);
}

static inline int PluQ_Vec3_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, PluQ_Vec3_identifier, 12, 4);
}

static inline int PluQ_Vec3_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, PluQ_Vec3_type_hash, 12, 4);
}

static inline int PluQ_Vec3_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, PluQ_Vec3_type_hash, 12, 4);
}

static inline int PluQ_Vec3_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 12, 4);
}

static inline int PluQ_Vec3_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root_with_size(buf, bufsiz, thash, 12, 4);
}

static inline int PluQ_Vec3_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 12, 4);
}

static inline int PluQ_Vec3_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root_with_size(buf, bufsiz, fid, 12, 4);
}

static int PluQ_ResourceRequest_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* resource_type */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* resource_id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* resource_name */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_ResourceRequest_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_ResourceRequest_identifier, &PluQ_ResourceRequest_verify_table);
}

static inline int PluQ_ResourceRequest_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_ResourceRequest_identifier, &PluQ_ResourceRequest_verify_table);
}

static inline int PluQ_ResourceRequest_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_ResourceRequest_type_identifier, &PluQ_ResourceRequest_verify_table);
}

static inline int PluQ_ResourceRequest_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_ResourceRequest_type_identifier, &PluQ_ResourceRequest_verify_table);
}

static inline int PluQ_ResourceRequest_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_ResourceRequest_verify_table);
}

static inline int PluQ_ResourceRequest_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_ResourceRequest_verify_table);
}

static inline int PluQ_ResourceRequest_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_ResourceRequest_verify_table);
}

static inline int PluQ_ResourceRequest_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_ResourceRequest_verify_table);
}

static int PluQ_Texture_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* width */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* height */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 1, 1) /* format */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 5, 0, 1, 1, INT64_C(4294967295)) /* pixels */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_Texture_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Texture_identifier, &PluQ_Texture_verify_table);
}

static inline int PluQ_Texture_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Texture_identifier, &PluQ_Texture_verify_table);
}

static inline int PluQ_Texture_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Texture_type_identifier, &PluQ_Texture_verify_table);
}

static inline int PluQ_Texture_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Texture_type_identifier, &PluQ_Texture_verify_table);
}

static inline int PluQ_Texture_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_Texture_verify_table);
}

static inline int PluQ_Texture_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_Texture_verify_table);
}

static inline int PluQ_Texture_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_Texture_verify_table);
}

static inline int PluQ_Texture_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_Texture_verify_table);
}

static int PluQ_Model_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* num_vertices */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* num_triangles */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 4, 4) /* num_frames */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 5, 0, 4, 4, INT64_C(1073741823)) /* vertices */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 6, 0, 2, 2, INT64_C(2147483647)) /* triangles */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 7, 0, 4, 4, INT64_C(1073741823)) /* texcoords */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 8, 0, 4, 4, INT64_C(1073741823)) /* normals */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_Model_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Model_identifier, &PluQ_Model_verify_table);
}

static inline int PluQ_Model_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Model_identifier, &PluQ_Model_verify_table);
}

static inline int PluQ_Model_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Model_type_identifier, &PluQ_Model_verify_table);
}

static inline int PluQ_Model_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Model_type_identifier, &PluQ_Model_verify_table);
}

static inline int PluQ_Model_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_Model_verify_table);
}

static inline int PluQ_Model_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_Model_verify_table);
}

static inline int PluQ_Model_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_Model_verify_table);
}

static inline int PluQ_Model_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_Model_verify_table);
}

static int PluQ_BSPVertices_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 12, 4, INT64_C(357913941)) /* vertices */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_BSPVertices_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_BSPVertices_identifier, &PluQ_BSPVertices_verify_table);
}

static inline int PluQ_BSPVertices_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_BSPVertices_identifier, &PluQ_BSPVertices_verify_table);
}

static inline int PluQ_BSPVertices_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_BSPVertices_type_identifier, &PluQ_BSPVertices_verify_table);
}

static inline int PluQ_BSPVertices_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_BSPVertices_type_identifier, &PluQ_BSPVertices_verify_table);
}

static inline int PluQ_BSPVertices_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_BSPVertices_verify_table);
}

static inline int PluQ_BSPVertices_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_BSPVertices_verify_table);
}

static inline int PluQ_BSPVertices_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_BSPVertices_verify_table);
}

static inline int PluQ_BSPVertices_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_BSPVertices_verify_table);
}

static int PluQ_BSPFace_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* plane_id */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* side */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* first_edge */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* num_edges */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* texture_id */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 4, 4) /* lightmap_offset */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 6, 0, 1, 1, INT64_C(4294967295)) /* styles */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_BSPFace_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_BSPFace_identifier, &PluQ_BSPFace_verify_table);
}

static inline int PluQ_BSPFace_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_BSPFace_identifier, &PluQ_BSPFace_verify_table);
}

static inline int PluQ_BSPFace_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_BSPFace_type_identifier, &PluQ_BSPFace_verify_table);
}

static inline int PluQ_BSPFace_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_BSPFace_type_identifier, &PluQ_BSPFace_verify_table);
}

static inline int PluQ_BSPFace_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_BSPFace_verify_table);
}

static inline int PluQ_BSPFace_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_BSPFace_verify_table);
}

static inline int PluQ_BSPFace_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_BSPFace_verify_table);
}

static inline int PluQ_BSPFace_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_BSPFace_verify_table);
}

static int PluQ_BSPFaces_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &PluQ_BSPFace_verify_table) /* faces */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_BSPFaces_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_BSPFaces_identifier, &PluQ_BSPFaces_verify_table);
}

static inline int PluQ_BSPFaces_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_BSPFaces_identifier, &PluQ_BSPFaces_verify_table);
}

static inline int PluQ_BSPFaces_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_BSPFaces_type_identifier, &PluQ_BSPFaces_verify_table);
}

static inline int PluQ_BSPFaces_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_BSPFaces_type_identifier, &PluQ_BSPFaces_verify_table);
}

static inline int PluQ_BSPFaces_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_BSPFaces_verify_table);
}

static inline int PluQ_BSPFaces_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_BSPFaces_verify_table);
}

static inline int PluQ_BSPFaces_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_BSPFaces_verify_table);
}

static inline int PluQ_BSPFaces_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_BSPFaces_verify_table);
}

static int PluQ_Lightmap_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* id */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* width */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* height */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 3, 0, 1, 1, INT64_C(4294967295)) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_Lightmap_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Lightmap_identifier, &PluQ_Lightmap_verify_table);
}

static inline int PluQ_Lightmap_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Lightmap_identifier, &PluQ_Lightmap_verify_table);
}

static inline int PluQ_Lightmap_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Lightmap_type_identifier, &PluQ_Lightmap_verify_table);
}

static inline int PluQ_Lightmap_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Lightmap_type_identifier, &PluQ_Lightmap_verify_table);
}

static inline int PluQ_Lightmap_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_Lightmap_verify_table);
}

static inline int PluQ_Lightmap_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_Lightmap_verify_table);
}

static inline int PluQ_Lightmap_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_Lightmap_verify_table);
}

static inline int PluQ_Lightmap_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_Lightmap_verify_table);
}

static int PluQ_ResourceInfo_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* id */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* type */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* size */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_ResourceInfo_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_ResourceInfo_identifier, &PluQ_ResourceInfo_verify_table);
}

static inline int PluQ_ResourceInfo_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_ResourceInfo_identifier, &PluQ_ResourceInfo_verify_table);
}

static inline int PluQ_ResourceInfo_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_ResourceInfo_type_identifier, &PluQ_ResourceInfo_verify_table);
}

static inline int PluQ_ResourceInfo_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_ResourceInfo_type_identifier, &PluQ_ResourceInfo_verify_table);
}

static inline int PluQ_ResourceInfo_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_ResourceInfo_verify_table);
}

static inline int PluQ_ResourceInfo_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_ResourceInfo_verify_table);
}

static inline int PluQ_ResourceInfo_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_ResourceInfo_verify_table);
}

static inline int PluQ_ResourceInfo_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_ResourceInfo_verify_table);
}

static int PluQ_ResourceResponse_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* resource_id */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 2, 0, &PluQ_ResourceData_union_verifier) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_ResourceResponse_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_ResourceResponse_identifier, &PluQ_ResourceResponse_verify_table);
}

static inline int PluQ_ResourceResponse_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_ResourceResponse_identifier, &PluQ_ResourceResponse_verify_table);
}

static inline int PluQ_ResourceResponse_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_ResourceResponse_type_identifier, &PluQ_ResourceResponse_verify_table);
}

static inline int PluQ_ResourceResponse_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_ResourceResponse_type_identifier, &PluQ_ResourceResponse_verify_table);
}

static inline int PluQ_ResourceResponse_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_ResourceResponse_verify_table);
}

static inline int PluQ_ResourceResponse_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_ResourceResponse_verify_table);
}

static inline int PluQ_ResourceResponse_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_ResourceResponse_verify_table);
}

static inline int PluQ_ResourceResponse_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_ResourceResponse_verify_table);
}

static int PluQ_MapChanged_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* mapname */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &PluQ_ResourceInfo_verify_table) /* resources */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_MapChanged_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_MapChanged_identifier, &PluQ_MapChanged_verify_table);
}

static inline int PluQ_MapChanged_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_MapChanged_identifier, &PluQ_MapChanged_verify_table);
}

static inline int PluQ_MapChanged_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_MapChanged_type_identifier, &PluQ_MapChanged_verify_table);
}

static inline int PluQ_MapChanged_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_MapChanged_type_identifier, &PluQ_MapChanged_verify_table);
}

static inline int PluQ_MapChanged_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_MapChanged_verify_table);
}

static inline int PluQ_MapChanged_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_MapChanged_verify_table);
}

static inline int PluQ_MapChanged_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_MapChanged_verify_table);
}

static inline int PluQ_MapChanged_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_MapChanged_verify_table);
}

static int PluQ_Disconnected_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* reason */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_Disconnected_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Disconnected_identifier, &PluQ_Disconnected_verify_table);
}

static inline int PluQ_Disconnected_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Disconnected_identifier, &PluQ_Disconnected_verify_table);
}

static inline int PluQ_Disconnected_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Disconnected_type_identifier, &PluQ_Disconnected_verify_table);
}

static inline int PluQ_Disconnected_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Disconnected_type_identifier, &PluQ_Disconnected_verify_table);
}

static inline int PluQ_Disconnected_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_Disconnected_verify_table);
}

static inline int PluQ_Disconnected_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_Disconnected_verify_table);
}

static inline int PluQ_Disconnected_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_Disconnected_verify_table);
}

static inline int PluQ_Disconnected_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_Disconnected_verify_table);
}

static int PluQ_Entity_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 12, 4) /* origin */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 12, 4) /* angles */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* model_id */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* frame */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 1, 1) /* colormap */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 1, 1) /* skin */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 4, 4) /* effects */)) return ret;
    if ((ret = flatcc_verify_field(td, 7, 4, 4) /* alpha */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_Entity_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Entity_identifier, &PluQ_Entity_verify_table);
}

static inline int PluQ_Entity_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Entity_identifier, &PluQ_Entity_verify_table);
}

static inline int PluQ_Entity_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_Entity_type_identifier, &PluQ_Entity_verify_table);
}

static inline int PluQ_Entity_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_Entity_type_identifier, &PluQ_Entity_verify_table);
}

static inline int PluQ_Entity_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_Entity_verify_table);
}

static inline int PluQ_Entity_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_Entity_verify_table);
}

static inline int PluQ_Entity_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_Entity_verify_table);
}

static inline int PluQ_Entity_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_Entity_verify_table);
}

static int PluQ_FrameUpdate_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* frame_number */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* timestamp */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 12, 4) /* view_origin */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 12, 4) /* view_angles */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* health */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 2, 2) /* armor */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 1, 1) /* weapon */)) return ret;
    if ((ret = flatcc_verify_field(td, 7, 2, 2) /* ammo */)) return ret;
    if ((ret = flatcc_verify_field(td, 8, 1, 1) /* paused */)) return ret;
    if ((ret = flatcc_verify_field(td, 9, 1, 1) /* in_game */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 10, 0, &PluQ_Entity_verify_table) /* entities */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_FrameUpdate_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_FrameUpdate_identifier, &PluQ_FrameUpdate_verify_table);
}

static inline int PluQ_FrameUpdate_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_FrameUpdate_identifier, &PluQ_FrameUpdate_verify_table);
}

static inline int PluQ_FrameUpdate_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_FrameUpdate_type_identifier, &PluQ_FrameUpdate_verify_table);
}

static inline int PluQ_FrameUpdate_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_FrameUpdate_type_identifier, &PluQ_FrameUpdate_verify_table);
}

static inline int PluQ_FrameUpdate_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_FrameUpdate_verify_table);
}

static inline int PluQ_FrameUpdate_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_FrameUpdate_verify_table);
}

static inline int PluQ_FrameUpdate_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_FrameUpdate_verify_table);
}

static inline int PluQ_FrameUpdate_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_FrameUpdate_verify_table);
}

static int PluQ_GameplayMessage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &PluQ_GameplayEvent_union_verifier) /* event */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_GameplayMessage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_GameplayMessage_identifier, &PluQ_GameplayMessage_verify_table);
}

static inline int PluQ_GameplayMessage_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_GameplayMessage_identifier, &PluQ_GameplayMessage_verify_table);
}

static inline int PluQ_GameplayMessage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_GameplayMessage_type_identifier, &PluQ_GameplayMessage_verify_table);
}

static inline int PluQ_GameplayMessage_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_GameplayMessage_type_identifier, &PluQ_GameplayMessage_verify_table);
}

static inline int PluQ_GameplayMessage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_GameplayMessage_verify_table);
}

static inline int PluQ_GameplayMessage_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_GameplayMessage_verify_table);
}

static inline int PluQ_GameplayMessage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_GameplayMessage_verify_table);
}

static inline int PluQ_GameplayMessage_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_GameplayMessage_verify_table);
}

static int PluQ_InputCommand_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* sequence */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* timestamp */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* forward_move */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* side_move */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 4, 4) /* up_move */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 12, 4) /* view_angles */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 4, 4) /* buttons */)) return ret;
    if ((ret = flatcc_verify_field(td, 7, 1, 1) /* impulse */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 8, 0) /* cmd_text */)) return ret;
    return flatcc_verify_ok;
}

static inline int PluQ_InputCommand_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_InputCommand_identifier, &PluQ_InputCommand_verify_table);
}

static inline int PluQ_InputCommand_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_InputCommand_identifier, &PluQ_InputCommand_verify_table);
}

static inline int PluQ_InputCommand_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PluQ_InputCommand_type_identifier, &PluQ_InputCommand_verify_table);
}

static inline int PluQ_InputCommand_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, PluQ_InputCommand_type_identifier, &PluQ_InputCommand_verify_table);
}

static inline int PluQ_InputCommand_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PluQ_InputCommand_verify_table);
}

static inline int PluQ_InputCommand_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &PluQ_InputCommand_verify_table);
}

static inline int PluQ_InputCommand_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PluQ_InputCommand_verify_table);
}

static inline int PluQ_InputCommand_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &PluQ_InputCommand_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PLUQ_VERIFIER_H */
