#ifndef PLUQ_READER_H
#define PLUQ_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

typedef struct PluQ_Vec3 PluQ_Vec3_t;
typedef const PluQ_Vec3_t *PluQ_Vec3_struct_t;
typedef PluQ_Vec3_t *PluQ_Vec3_mutable_struct_t;
typedef const PluQ_Vec3_t *PluQ_Vec3_vec_t;
typedef PluQ_Vec3_t *PluQ_Vec3_mutable_vec_t;

typedef const struct PluQ_ResourceRequest_table *PluQ_ResourceRequest_table_t;
typedef struct PluQ_ResourceRequest_table *PluQ_ResourceRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_ResourceRequest_vec_t;
typedef flatbuffers_uoffset_t *PluQ_ResourceRequest_mutable_vec_t;
typedef const struct PluQ_Texture_table *PluQ_Texture_table_t;
typedef struct PluQ_Texture_table *PluQ_Texture_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_Texture_vec_t;
typedef flatbuffers_uoffset_t *PluQ_Texture_mutable_vec_t;
typedef const struct PluQ_Model_table *PluQ_Model_table_t;
typedef struct PluQ_Model_table *PluQ_Model_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_Model_vec_t;
typedef flatbuffers_uoffset_t *PluQ_Model_mutable_vec_t;
typedef const struct PluQ_BSPVertices_table *PluQ_BSPVertices_table_t;
typedef struct PluQ_BSPVertices_table *PluQ_BSPVertices_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_BSPVertices_vec_t;
typedef flatbuffers_uoffset_t *PluQ_BSPVertices_mutable_vec_t;
typedef const struct PluQ_BSPFace_table *PluQ_BSPFace_table_t;
typedef struct PluQ_BSPFace_table *PluQ_BSPFace_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_BSPFace_vec_t;
typedef flatbuffers_uoffset_t *PluQ_BSPFace_mutable_vec_t;
typedef const struct PluQ_BSPFaces_table *PluQ_BSPFaces_table_t;
typedef struct PluQ_BSPFaces_table *PluQ_BSPFaces_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_BSPFaces_vec_t;
typedef flatbuffers_uoffset_t *PluQ_BSPFaces_mutable_vec_t;
typedef const struct PluQ_Lightmap_table *PluQ_Lightmap_table_t;
typedef struct PluQ_Lightmap_table *PluQ_Lightmap_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_Lightmap_vec_t;
typedef flatbuffers_uoffset_t *PluQ_Lightmap_mutable_vec_t;
typedef const struct PluQ_ResourceInfo_table *PluQ_ResourceInfo_table_t;
typedef struct PluQ_ResourceInfo_table *PluQ_ResourceInfo_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_ResourceInfo_vec_t;
typedef flatbuffers_uoffset_t *PluQ_ResourceInfo_mutable_vec_t;
typedef const struct PluQ_ResourceResponse_table *PluQ_ResourceResponse_table_t;
typedef struct PluQ_ResourceResponse_table *PluQ_ResourceResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_ResourceResponse_vec_t;
typedef flatbuffers_uoffset_t *PluQ_ResourceResponse_mutable_vec_t;
typedef const struct PluQ_MapChanged_table *PluQ_MapChanged_table_t;
typedef struct PluQ_MapChanged_table *PluQ_MapChanged_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_MapChanged_vec_t;
typedef flatbuffers_uoffset_t *PluQ_MapChanged_mutable_vec_t;
typedef const struct PluQ_Disconnected_table *PluQ_Disconnected_table_t;
typedef struct PluQ_Disconnected_table *PluQ_Disconnected_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_Disconnected_vec_t;
typedef flatbuffers_uoffset_t *PluQ_Disconnected_mutable_vec_t;
typedef const struct PluQ_Entity_table *PluQ_Entity_table_t;
typedef struct PluQ_Entity_table *PluQ_Entity_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_Entity_vec_t;
typedef flatbuffers_uoffset_t *PluQ_Entity_mutable_vec_t;
typedef const struct PluQ_FrameUpdate_table *PluQ_FrameUpdate_table_t;
typedef struct PluQ_FrameUpdate_table *PluQ_FrameUpdate_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_FrameUpdate_vec_t;
typedef flatbuffers_uoffset_t *PluQ_FrameUpdate_mutable_vec_t;
typedef const struct PluQ_GameplayMessage_table *PluQ_GameplayMessage_table_t;
typedef struct PluQ_GameplayMessage_table *PluQ_GameplayMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_GameplayMessage_vec_t;
typedef flatbuffers_uoffset_t *PluQ_GameplayMessage_mutable_vec_t;
typedef const struct PluQ_InputCommand_table *PluQ_InputCommand_table_t;
typedef struct PluQ_InputCommand_table *PluQ_InputCommand_mutable_table_t;
typedef const flatbuffers_uoffset_t *PluQ_InputCommand_vec_t;
typedef flatbuffers_uoffset_t *PluQ_InputCommand_mutable_vec_t;
#ifndef PluQ_Vec3_file_identifier
#define PluQ_Vec3_file_identifier 0
#endif
/* deprecated, use PluQ_Vec3_file_identifier */
#ifndef PluQ_Vec3_identifier
#define PluQ_Vec3_identifier 0
#endif
#define PluQ_Vec3_type_hash ((flatbuffers_thash_t)0x3c53ec4c)
#define PluQ_Vec3_type_identifier "\x4c\xec\x53\x3c"
#ifndef PluQ_Vec3_file_extension
#define PluQ_Vec3_file_extension "bin"
#endif
#ifndef PluQ_ResourceRequest_file_identifier
#define PluQ_ResourceRequest_file_identifier 0
#endif
/* deprecated, use PluQ_ResourceRequest_file_identifier */
#ifndef PluQ_ResourceRequest_identifier
#define PluQ_ResourceRequest_identifier 0
#endif
#define PluQ_ResourceRequest_type_hash ((flatbuffers_thash_t)0x9be30000)
#define PluQ_ResourceRequest_type_identifier "\x00\x00\xe3\x9b"
#ifndef PluQ_ResourceRequest_file_extension
#define PluQ_ResourceRequest_file_extension "bin"
#endif
#ifndef PluQ_Texture_file_identifier
#define PluQ_Texture_file_identifier 0
#endif
/* deprecated, use PluQ_Texture_file_identifier */
#ifndef PluQ_Texture_identifier
#define PluQ_Texture_identifier 0
#endif
#define PluQ_Texture_type_hash ((flatbuffers_thash_t)0xeb225782)
#define PluQ_Texture_type_identifier "\x82\x57\x22\xeb"
#ifndef PluQ_Texture_file_extension
#define PluQ_Texture_file_extension "bin"
#endif
#ifndef PluQ_Model_file_identifier
#define PluQ_Model_file_identifier 0
#endif
/* deprecated, use PluQ_Model_file_identifier */
#ifndef PluQ_Model_identifier
#define PluQ_Model_identifier 0
#endif
#define PluQ_Model_type_hash ((flatbuffers_thash_t)0x1242e5d0)
#define PluQ_Model_type_identifier "\xd0\xe5\x42\x12"
#ifndef PluQ_Model_file_extension
#define PluQ_Model_file_extension "bin"
#endif
#ifndef PluQ_BSPVertices_file_identifier
#define PluQ_BSPVertices_file_identifier 0
#endif
/* deprecated, use PluQ_BSPVertices_file_identifier */
#ifndef PluQ_BSPVertices_identifier
#define PluQ_BSPVertices_identifier 0
#endif
#define PluQ_BSPVertices_type_hash ((flatbuffers_thash_t)0x5efe1fbf)
#define PluQ_BSPVertices_type_identifier "\xbf\x1f\xfe\x5e"
#ifndef PluQ_BSPVertices_file_extension
#define PluQ_BSPVertices_file_extension "bin"
#endif
#ifndef PluQ_BSPFace_file_identifier
#define PluQ_BSPFace_file_identifier 0
#endif
/* deprecated, use PluQ_BSPFace_file_identifier */
#ifndef PluQ_BSPFace_identifier
#define PluQ_BSPFace_identifier 0
#endif
#define PluQ_BSPFace_type_hash ((flatbuffers_thash_t)0xad522281)
#define PluQ_BSPFace_type_identifier "\x81\x22\x52\xad"
#ifndef PluQ_BSPFace_file_extension
#define PluQ_BSPFace_file_extension "bin"
#endif
#ifndef PluQ_BSPFaces_file_identifier
#define PluQ_BSPFaces_file_identifier 0
#endif
/* deprecated, use PluQ_BSPFaces_file_identifier */
#ifndef PluQ_BSPFaces_identifier
#define PluQ_BSPFaces_identifier 0
#endif
#define PluQ_BSPFaces_type_hash ((flatbuffers_thash_t)0xca4d02f6)
#define PluQ_BSPFaces_type_identifier "\xf6\x02\x4d\xca"
#ifndef PluQ_BSPFaces_file_extension
#define PluQ_BSPFaces_file_extension "bin"
#endif
#ifndef PluQ_Lightmap_file_identifier
#define PluQ_Lightmap_file_identifier 0
#endif
/* deprecated, use PluQ_Lightmap_file_identifier */
#ifndef PluQ_Lightmap_identifier
#define PluQ_Lightmap_identifier 0
#endif
#define PluQ_Lightmap_type_hash ((flatbuffers_thash_t)0x56258389)
#define PluQ_Lightmap_type_identifier "\x89\x83\x25\x56"
#ifndef PluQ_Lightmap_file_extension
#define PluQ_Lightmap_file_extension "bin"
#endif
#ifndef PluQ_ResourceInfo_file_identifier
#define PluQ_ResourceInfo_file_identifier 0
#endif
/* deprecated, use PluQ_ResourceInfo_file_identifier */
#ifndef PluQ_ResourceInfo_identifier
#define PluQ_ResourceInfo_identifier 0
#endif
#define PluQ_ResourceInfo_type_hash ((flatbuffers_thash_t)0x5e67a12b)
#define PluQ_ResourceInfo_type_identifier "\x2b\xa1\x67\x5e"
#ifndef PluQ_ResourceInfo_file_extension
#define PluQ_ResourceInfo_file_extension "bin"
#endif
#ifndef PluQ_ResourceResponse_file_identifier
#define PluQ_ResourceResponse_file_identifier 0
#endif
/* deprecated, use PluQ_ResourceResponse_file_identifier */
#ifndef PluQ_ResourceResponse_identifier
#define PluQ_ResourceResponse_identifier 0
#endif
#define PluQ_ResourceResponse_type_hash ((flatbuffers_thash_t)0xb4d8750c)
#define PluQ_ResourceResponse_type_identifier "\x0c\x75\xd8\xb4"
#ifndef PluQ_ResourceResponse_file_extension
#define PluQ_ResourceResponse_file_extension "bin"
#endif
#ifndef PluQ_MapChanged_file_identifier
#define PluQ_MapChanged_file_identifier 0
#endif
/* deprecated, use PluQ_MapChanged_file_identifier */
#ifndef PluQ_MapChanged_identifier
#define PluQ_MapChanged_identifier 0
#endif
#define PluQ_MapChanged_type_hash ((flatbuffers_thash_t)0x89443919)
#define PluQ_MapChanged_type_identifier "\x19\x39\x44\x89"
#ifndef PluQ_MapChanged_file_extension
#define PluQ_MapChanged_file_extension "bin"
#endif
#ifndef PluQ_Disconnected_file_identifier
#define PluQ_Disconnected_file_identifier 0
#endif
/* deprecated, use PluQ_Disconnected_file_identifier */
#ifndef PluQ_Disconnected_identifier
#define PluQ_Disconnected_identifier 0
#endif
#define PluQ_Disconnected_type_hash ((flatbuffers_thash_t)0x73e020d0)
#define PluQ_Disconnected_type_identifier "\xd0\x20\xe0\x73"
#ifndef PluQ_Disconnected_file_extension
#define PluQ_Disconnected_file_extension "bin"
#endif
#ifndef PluQ_Entity_file_identifier
#define PluQ_Entity_file_identifier 0
#endif
/* deprecated, use PluQ_Entity_file_identifier */
#ifndef PluQ_Entity_identifier
#define PluQ_Entity_identifier 0
#endif
#define PluQ_Entity_type_hash ((flatbuffers_thash_t)0x2ab08aac)
#define PluQ_Entity_type_identifier "\xac\x8a\xb0\x2a"
#ifndef PluQ_Entity_file_extension
#define PluQ_Entity_file_extension "bin"
#endif
#ifndef PluQ_FrameUpdate_file_identifier
#define PluQ_FrameUpdate_file_identifier 0
#endif
/* deprecated, use PluQ_FrameUpdate_file_identifier */
#ifndef PluQ_FrameUpdate_identifier
#define PluQ_FrameUpdate_identifier 0
#endif
#define PluQ_FrameUpdate_type_hash ((flatbuffers_thash_t)0xecd86039)
#define PluQ_FrameUpdate_type_identifier "\x39\x60\xd8\xec"
#ifndef PluQ_FrameUpdate_file_extension
#define PluQ_FrameUpdate_file_extension "bin"
#endif
#ifndef PluQ_GameplayMessage_file_identifier
#define PluQ_GameplayMessage_file_identifier 0
#endif
/* deprecated, use PluQ_GameplayMessage_file_identifier */
#ifndef PluQ_GameplayMessage_identifier
#define PluQ_GameplayMessage_identifier 0
#endif
#define PluQ_GameplayMessage_type_hash ((flatbuffers_thash_t)0xce153bf6)
#define PluQ_GameplayMessage_type_identifier "\xf6\x3b\x15\xce"
#ifndef PluQ_GameplayMessage_file_extension
#define PluQ_GameplayMessage_file_extension "bin"
#endif
#ifndef PluQ_InputCommand_file_identifier
#define PluQ_InputCommand_file_identifier 0
#endif
/* deprecated, use PluQ_InputCommand_file_identifier */
#ifndef PluQ_InputCommand_identifier
#define PluQ_InputCommand_identifier 0
#endif
#define PluQ_InputCommand_type_hash ((flatbuffers_thash_t)0xc961195e)
#define PluQ_InputCommand_type_identifier "\x5e\x19\x61\xc9"
#ifndef PluQ_InputCommand_file_extension
#define PluQ_InputCommand_file_extension "bin"
#endif

typedef int8_t PluQ_ResourceType_enum_t;
__flatbuffers_define_integer_type(PluQ_ResourceType, PluQ_ResourceType_enum_t, 8)
#define PluQ_ResourceType_None ((PluQ_ResourceType_enum_t)INT8_C(0))
#define PluQ_ResourceType_Texture ((PluQ_ResourceType_enum_t)INT8_C(1))
#define PluQ_ResourceType_Model ((PluQ_ResourceType_enum_t)INT8_C(2))
#define PluQ_ResourceType_BSPVertices ((PluQ_ResourceType_enum_t)INT8_C(3))
#define PluQ_ResourceType_BSPFaces ((PluQ_ResourceType_enum_t)INT8_C(4))
#define PluQ_ResourceType_Lightmap ((PluQ_ResourceType_enum_t)INT8_C(5))

static inline const char *PluQ_ResourceType_name(PluQ_ResourceType_enum_t value)
{
    switch (value) {
    case PluQ_ResourceType_None: return "None";
    case PluQ_ResourceType_Texture: return "Texture";
    case PluQ_ResourceType_Model: return "Model";
    case PluQ_ResourceType_BSPVertices: return "BSPVertices";
    case PluQ_ResourceType_BSPFaces: return "BSPFaces";
    case PluQ_ResourceType_Lightmap: return "Lightmap";
    default: return "";
    }
}

static inline int PluQ_ResourceType_is_known_value(PluQ_ResourceType_enum_t value)
{
    switch (value) {
    case PluQ_ResourceType_None: return 1;
    case PluQ_ResourceType_Texture: return 1;
    case PluQ_ResourceType_Model: return 1;
    case PluQ_ResourceType_BSPVertices: return 1;
    case PluQ_ResourceType_BSPFaces: return 1;
    case PluQ_ResourceType_Lightmap: return 1;
    default: return 0;
    }
}


struct PluQ_Vec3 {
    alignas(4) float x;
    alignas(4) float y;
    alignas(4) float z;
};
static_assert(sizeof(PluQ_Vec3_t) == 12, "struct size mismatch");

static inline const PluQ_Vec3_t *PluQ_Vec3__const_ptr_add(const PluQ_Vec3_t *p, size_t i) { return p + i; }
static inline PluQ_Vec3_t *PluQ_Vec3__ptr_add(PluQ_Vec3_t *p, size_t i) { return p + i; }
static inline PluQ_Vec3_struct_t PluQ_Vec3_vec_at(PluQ_Vec3_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t PluQ_Vec3__size(void) { return 12; }
static inline size_t PluQ_Vec3_vec_len(PluQ_Vec3_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(PluQ_Vec3)

__flatbuffers_define_struct_scalar_field(PluQ_Vec3, x, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PluQ_Vec3, y, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PluQ_Vec3, z, flatbuffers_float, float)


struct PluQ_ResourceRequest_table { uint8_t unused__; };

static inline size_t PluQ_ResourceRequest_vec_len(PluQ_ResourceRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_ResourceRequest_table_t PluQ_ResourceRequest_vec_at(PluQ_ResourceRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_ResourceRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_ResourceRequest)

__flatbuffers_define_scalar_field(0, PluQ_ResourceRequest, resource_type, PluQ_ResourceType, PluQ_ResourceType_enum_t, INT8_C(0))
__flatbuffers_define_scalar_field(1, PluQ_ResourceRequest, resource_id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_string_field(2, PluQ_ResourceRequest, resource_name, 0)

struct PluQ_Texture_table { uint8_t unused__; };

static inline size_t PluQ_Texture_vec_len(PluQ_Texture_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_Texture_table_t PluQ_Texture_vec_at(PluQ_Texture_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_Texture_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_Texture)

__flatbuffers_define_scalar_field(0, PluQ_Texture, id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_string_field(1, PluQ_Texture, name, 0)
__flatbuffers_define_scalar_field(2, PluQ_Texture, width, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(3, PluQ_Texture, height, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(4, PluQ_Texture, format, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_vector_field(5, PluQ_Texture, pixels, flatbuffers_uint8_vec_t, 0)

struct PluQ_Model_table { uint8_t unused__; };

static inline size_t PluQ_Model_vec_len(PluQ_Model_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_Model_table_t PluQ_Model_vec_at(PluQ_Model_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_Model_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_Model)

__flatbuffers_define_scalar_field(0, PluQ_Model, id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_string_field(1, PluQ_Model, name, 0)
__flatbuffers_define_scalar_field(2, PluQ_Model, num_vertices, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(3, PluQ_Model, num_triangles, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(4, PluQ_Model, num_frames, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_vector_field(5, PluQ_Model, vertices, flatbuffers_float_vec_t, 0)
__flatbuffers_define_vector_field(6, PluQ_Model, triangles, flatbuffers_uint16_vec_t, 0)
__flatbuffers_define_vector_field(7, PluQ_Model, texcoords, flatbuffers_float_vec_t, 0)
__flatbuffers_define_vector_field(8, PluQ_Model, normals, flatbuffers_float_vec_t, 0)

struct PluQ_BSPVertices_table { uint8_t unused__; };

static inline size_t PluQ_BSPVertices_vec_len(PluQ_BSPVertices_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_BSPVertices_table_t PluQ_BSPVertices_vec_at(PluQ_BSPVertices_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_BSPVertices_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_BSPVertices)

__flatbuffers_define_vector_field(0, PluQ_BSPVertices, vertices, PluQ_Vec3_vec_t, 0)

struct PluQ_BSPFace_table { uint8_t unused__; };

static inline size_t PluQ_BSPFace_vec_len(PluQ_BSPFace_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_BSPFace_table_t PluQ_BSPFace_vec_at(PluQ_BSPFace_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_BSPFace_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_BSPFace)

__flatbuffers_define_scalar_field(0, PluQ_BSPFace, plane_id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, PluQ_BSPFace, side, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(2, PluQ_BSPFace, first_edge, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(3, PluQ_BSPFace, num_edges, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(4, PluQ_BSPFace, texture_id, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(5, PluQ_BSPFace, lightmap_offset, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_vector_field(6, PluQ_BSPFace, styles, flatbuffers_int8_vec_t, 0)

struct PluQ_BSPFaces_table { uint8_t unused__; };

static inline size_t PluQ_BSPFaces_vec_len(PluQ_BSPFaces_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_BSPFaces_table_t PluQ_BSPFaces_vec_at(PluQ_BSPFaces_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_BSPFaces_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_BSPFaces)

__flatbuffers_define_vector_field(0, PluQ_BSPFaces, faces, PluQ_BSPFace_vec_t, 0)

struct PluQ_Lightmap_table { uint8_t unused__; };

static inline size_t PluQ_Lightmap_vec_len(PluQ_Lightmap_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_Lightmap_table_t PluQ_Lightmap_vec_at(PluQ_Lightmap_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_Lightmap_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_Lightmap)

__flatbuffers_define_scalar_field(0, PluQ_Lightmap, id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, PluQ_Lightmap, width, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(2, PluQ_Lightmap, height, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_vector_field(3, PluQ_Lightmap, data, flatbuffers_uint8_vec_t, 0)

struct PluQ_ResourceInfo_table { uint8_t unused__; };

static inline size_t PluQ_ResourceInfo_vec_len(PluQ_ResourceInfo_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_ResourceInfo_table_t PluQ_ResourceInfo_vec_at(PluQ_ResourceInfo_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_ResourceInfo_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_ResourceInfo)

__flatbuffers_define_scalar_field(0, PluQ_ResourceInfo, id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, PluQ_ResourceInfo, type, PluQ_ResourceType, PluQ_ResourceType_enum_t, INT8_C(0))
__flatbuffers_define_string_field(2, PluQ_ResourceInfo, name, 0)
__flatbuffers_define_scalar_field(3, PluQ_ResourceInfo, size, flatbuffers_uint32, uint32_t, UINT32_C(0))
typedef uint8_t PluQ_ResourceData_union_type_t;
__flatbuffers_define_integer_type(PluQ_ResourceData, PluQ_ResourceData_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, PluQ_ResourceData)
#define PluQ_ResourceData_NONE ((PluQ_ResourceData_union_type_t)UINT8_C(0))
#define PluQ_ResourceData_Texture ((PluQ_ResourceData_union_type_t)UINT8_C(1))
#define PluQ_ResourceData_Model ((PluQ_ResourceData_union_type_t)UINT8_C(2))
#define PluQ_ResourceData_BSPVertices ((PluQ_ResourceData_union_type_t)UINT8_C(3))
#define PluQ_ResourceData_BSPFaces ((PluQ_ResourceData_union_type_t)UINT8_C(4))
#define PluQ_ResourceData_Lightmap ((PluQ_ResourceData_union_type_t)UINT8_C(5))

static inline const char *PluQ_ResourceData_type_name(PluQ_ResourceData_union_type_t type)
{
    switch (type) {
    case PluQ_ResourceData_NONE: return "NONE";
    case PluQ_ResourceData_Texture: return "Texture";
    case PluQ_ResourceData_Model: return "Model";
    case PluQ_ResourceData_BSPVertices: return "BSPVertices";
    case PluQ_ResourceData_BSPFaces: return "BSPFaces";
    case PluQ_ResourceData_Lightmap: return "Lightmap";
    default: return "";
    }
}

static inline int PluQ_ResourceData_is_known_type(PluQ_ResourceData_union_type_t type)
{
    switch (type) {
    case PluQ_ResourceData_NONE: return 1;
    case PluQ_ResourceData_Texture: return 1;
    case PluQ_ResourceData_Model: return 1;
    case PluQ_ResourceData_BSPVertices: return 1;
    case PluQ_ResourceData_BSPFaces: return 1;
    case PluQ_ResourceData_Lightmap: return 1;
    default: return 0;
    }
}


struct PluQ_ResourceResponse_table { uint8_t unused__; };

static inline size_t PluQ_ResourceResponse_vec_len(PluQ_ResourceResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_ResourceResponse_table_t PluQ_ResourceResponse_vec_at(PluQ_ResourceResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_ResourceResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_ResourceResponse)

__flatbuffers_define_scalar_field(0, PluQ_ResourceResponse, resource_id, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_union_field(flatbuffers_, 2, PluQ_ResourceResponse, data, PluQ_ResourceData, 0)

struct PluQ_MapChanged_table { uint8_t unused__; };

static inline size_t PluQ_MapChanged_vec_len(PluQ_MapChanged_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_MapChanged_table_t PluQ_MapChanged_vec_at(PluQ_MapChanged_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_MapChanged_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_MapChanged)

__flatbuffers_define_string_field(0, PluQ_MapChanged, mapname, 0)
__flatbuffers_define_vector_field(1, PluQ_MapChanged, resources, PluQ_ResourceInfo_vec_t, 0)

struct PluQ_Disconnected_table { uint8_t unused__; };

static inline size_t PluQ_Disconnected_vec_len(PluQ_Disconnected_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_Disconnected_table_t PluQ_Disconnected_vec_at(PluQ_Disconnected_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_Disconnected_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_Disconnected)

__flatbuffers_define_string_field(0, PluQ_Disconnected, reason, 0)

struct PluQ_Entity_table { uint8_t unused__; };

static inline size_t PluQ_Entity_vec_len(PluQ_Entity_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_Entity_table_t PluQ_Entity_vec_at(PluQ_Entity_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_Entity_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_Entity)

__flatbuffers_define_struct_field(0, PluQ_Entity, origin, PluQ_Vec3_struct_t, 0)
__flatbuffers_define_struct_field(1, PluQ_Entity, angles, PluQ_Vec3_struct_t, 0)
__flatbuffers_define_scalar_field(2, PluQ_Entity, model_id, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(3, PluQ_Entity, frame, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(4, PluQ_Entity, colormap, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(5, PluQ_Entity, skin, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(6, PluQ_Entity, effects, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(7, PluQ_Entity, alpha, flatbuffers_float, float, 0.00000000f)

struct PluQ_FrameUpdate_table { uint8_t unused__; };

static inline size_t PluQ_FrameUpdate_vec_len(PluQ_FrameUpdate_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_FrameUpdate_table_t PluQ_FrameUpdate_vec_at(PluQ_FrameUpdate_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_FrameUpdate_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_FrameUpdate)

__flatbuffers_define_scalar_field(0, PluQ_FrameUpdate, frame_number, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, PluQ_FrameUpdate, timestamp, flatbuffers_double, double, 0.0000000000000000)
__flatbuffers_define_struct_field(2, PluQ_FrameUpdate, view_origin, PluQ_Vec3_struct_t, 0)
__flatbuffers_define_struct_field(3, PluQ_FrameUpdate, view_angles, PluQ_Vec3_struct_t, 0)
__flatbuffers_define_scalar_field(4, PluQ_FrameUpdate, health, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(5, PluQ_FrameUpdate, armor, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(6, PluQ_FrameUpdate, weapon, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_scalar_field(7, PluQ_FrameUpdate, ammo, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(8, PluQ_FrameUpdate, paused, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_scalar_field(9, PluQ_FrameUpdate, in_game, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_vector_field(10, PluQ_FrameUpdate, entities, PluQ_Entity_vec_t, 0)
typedef uint8_t PluQ_GameplayEvent_union_type_t;
__flatbuffers_define_integer_type(PluQ_GameplayEvent, PluQ_GameplayEvent_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, PluQ_GameplayEvent)
#define PluQ_GameplayEvent_NONE ((PluQ_GameplayEvent_union_type_t)UINT8_C(0))
#define PluQ_GameplayEvent_MapChanged ((PluQ_GameplayEvent_union_type_t)UINT8_C(1))
#define PluQ_GameplayEvent_FrameUpdate ((PluQ_GameplayEvent_union_type_t)UINT8_C(2))
#define PluQ_GameplayEvent_Disconnected ((PluQ_GameplayEvent_union_type_t)UINT8_C(3))

static inline const char *PluQ_GameplayEvent_type_name(PluQ_GameplayEvent_union_type_t type)
{
    switch (type) {
    case PluQ_GameplayEvent_NONE: return "NONE";
    case PluQ_GameplayEvent_MapChanged: return "MapChanged";
    case PluQ_GameplayEvent_FrameUpdate: return "FrameUpdate";
    case PluQ_GameplayEvent_Disconnected: return "Disconnected";
    default: return "";
    }
}

static inline int PluQ_GameplayEvent_is_known_type(PluQ_GameplayEvent_union_type_t type)
{
    switch (type) {
    case PluQ_GameplayEvent_NONE: return 1;
    case PluQ_GameplayEvent_MapChanged: return 1;
    case PluQ_GameplayEvent_FrameUpdate: return 1;
    case PluQ_GameplayEvent_Disconnected: return 1;
    default: return 0;
    }
}


struct PluQ_GameplayMessage_table { uint8_t unused__; };

static inline size_t PluQ_GameplayMessage_vec_len(PluQ_GameplayMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_GameplayMessage_table_t PluQ_GameplayMessage_vec_at(PluQ_GameplayMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_GameplayMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_GameplayMessage)

__flatbuffers_define_union_field(flatbuffers_, 1, PluQ_GameplayMessage, event, PluQ_GameplayEvent, 0)

struct PluQ_InputCommand_table { uint8_t unused__; };

static inline size_t PluQ_InputCommand_vec_len(PluQ_InputCommand_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PluQ_InputCommand_table_t PluQ_InputCommand_vec_at(PluQ_InputCommand_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PluQ_InputCommand_table_t, vec, i, 0)
__flatbuffers_table_as_root(PluQ_InputCommand)

__flatbuffers_define_scalar_field(0, PluQ_InputCommand, sequence, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, PluQ_InputCommand, timestamp, flatbuffers_double, double, 0.0000000000000000)
__flatbuffers_define_scalar_field(2, PluQ_InputCommand, forward_move, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(3, PluQ_InputCommand, side_move, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(4, PluQ_InputCommand, up_move, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_struct_field(5, PluQ_InputCommand, view_angles, PluQ_Vec3_struct_t, 0)
__flatbuffers_define_scalar_field(6, PluQ_InputCommand, buttons, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(7, PluQ_InputCommand, impulse, flatbuffers_int8, int8_t, INT8_C(0))
__flatbuffers_define_string_field(8, PluQ_InputCommand, cmd_text, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* PLUQ_READER_H */
