name: CMake on multiple platforms
on: [workflow_dispatch]
jobs:
  build: 
    name: Build Windows Visual Studio
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        c_compiler: [cl]

    steps:
      - name: Build
        run: |
        cmake -B build -DCMAKE_C_COMPILE=${{ matrix.c_compiler }} -DCMKE_BUILD_TYPE=${{matrix.build_type}}
