name: Windows CI
on: [push, pull_request]
jobs:
  build:
    name: Windows / ${{ matrix.platform }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, Win32]
    steps:
    - uses: actions/checkout@v4
    - name: Set environment variables
      run: |
        $gitrev = $(git describe --always)
        $gitbranch = $(git branch --show-current)
        $ver_suffix = ("$gitbranch" -eq "carnifex" -Or "$gitbranch" -eq "main") ? "-$gitrev" : "-$gitbranch-$gitrev"
        $platform_alt = ("${{matrix.platform}}" -eq "x64") ? "win64" : "win32"
        $platform_short = ("${{matrix.platform}}" -eq "Win32") ? "x86" : "${{matrix.platform}}"
        $build_artifact = "carnifex${ver_suffix}-${platform_alt}"
        echo "VER_SUFFIX=$ver_suffix" >> ${env:GITHUB_ENV}
        echo "BUILD_ARTIFACT=$build_artifact" >> ${env:GITHUB_ENV}
        echo "BUILD_DIR=$build_artifact" >> ${env:GITHUB_ENV}
        echo "PLATFORM_ALT=$platform_alt" >> ${env:GITHUB_ENV}
        echo "PLATFORM_SHORT=$platform_short" >> ${env:GITHUB_ENV}
        echo "ForceImportBeforeCppTargets=${env:GITHUB_WORKSPACE}\platforms\Windows\VisualStudio\custom_build.props" >> ${env:GITHUB_ENV}
    - name: Install CMake
      uses: lukka/run-cmake@v4
      with:
        cmakeListsTxtPath: CMakeLists.txt
        buildDirectory: build-artifacts
        buildType: Release
    - name: Build Carnifex Engine
      run: |
        $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $msbuild = & "$vswhere" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1
        $options = @( `
          '-property:Configuration=Release', `
          '-property:Platform=${{ matrix.platform }}', `
          '-maxcpucount', `
          '-verbosity:minimal' `
        )
        & $msbuild platforms\Windows\VisualStudio\carnifex.sln $options
        if (-not $?) { throw "Build failed" }
    - name: Test Engine
      run: |
        # Basic smoke test - check if engine starts without crashing
        $timeout = 10
        $process = Start-Process -FilePath "platforms\Windows\VisualStudio\${env:BUILD_DIR}\carnifex-engine.exe" -ArgumentList "-game", "carnifex-game", "-dev" -PassThru
        Start-Sleep -Seconds $timeout
        if (-not $process.HasExited) {
          $process.Kill()
        }
    - name: Prepare archive
      if: github.ref == 'refs/heads/carnifex' && github.event_name != 'pull_request'
      run: |
            $compiledir = "platforms\Windows\VisualStudio\${env:BUILD_DIR}"
            $zipdir = "artifact\${env:BUILD_ARTIFACT}"
            mkdir $zipdir | out-null
            copy ${compiledir}\*.exe $zipdir
            copy ${compiledir}\*.dll $zipdir
            copy carnifex-game\*.pak $zipdir -ErrorAction SilentlyContinue
            copy README.md $zipdir
            copy LICENSE.txt $zipdir
            copy docs\user\CARNIFEX_CREDITS.md $zipdir
    - name: Upload archive
      if: github.ref == 'refs/heads/carnifex' && github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BUILD_ARTIFACT }}
        path: artifact/*
